export const projectData = {
  en: [
    {
      img: "https://s6.uupload.ir/files/capture_ib.png",
      title: "Custom CMD",
      body: "A powerful command-line tool for managing nested route aliases effortlessly. Simplifies adding, removing, and modifying routes with an intuitive CLI interface.",
      link: "https://custom-cmd.tahanabavi.ir",
      github: "https://github.com/TahaNabavi/custom-cmd",
    },
    {
      img: "https://s6.uupload.ir/files/capture_a2yy.png",
      title: "Resume Website",
      body: "A sleek, responsive resume website showcasing my skills, projects, and experience. Built with modern web technologies for speed and style.",
      link: "https://resume-v1.tahanabavi.ir/",
      github: "",
    },
    {
      img: "https://s6.uupload.ir/files/capture_pq74.png",
      title: "Icon Animation Tool",
      body: "Create stunning SVG icon animations easily. Perfect for designers and developers adding dynamic visuals to projects.",
      link: "https://ico-animation.tahanabavi.ir/",
      github: "",
    },
    {
      img: "https://s6.uupload.ir/files/val_jb04.png",
      title: "Vaultify",
      body: "Securely store passwords, tasks, and notes with advanced encryption. Never lose important info again! 🚀🔒",
      link: "https://vaultify.tahanabavi.ir/",
      github: "https://github.com/TahaNabavi/vaultify-client",
    },
    {
      img: "https://camo.githubusercontent.com/a5d6e93b5aa0c13861e0d2de5b9307c4974980d303b779d8f4a24a712cd7aa5c/68747470733a2f2f73382e7575706c6f61642e69722f66696c65732f70315f7539656f2e706e67",
      title: "IRGAME shop",
      body: "Purchase Steam games, gift cards, and digital products securely. A seamless shopping experience for gamers.",
      link: "",
      github: "https://github.com/TahaNabavi/iran-game",
    },
    {
      img: "https://s8.uupload.ir/files/pr1_7rjx.jpg",
      title: "Resume Website",
      body: "A modern resume site built with Next.js, showcasing projects and skills in a clean, responsive design.",
      link: "https://portfolio-gamma-flax-82.vercel.app/",
      github: "",
    },
    {
      img: "https://s8.uupload.ir/files/capture_0tpd.png",
      title: "Game Server Status",
      body: "Real-time game server status dashboard. Check server availability, performance, and player stats.",
      link: "https://dark-game-pearl.vercel.app/",
      github: "https://github.com/TahaNabavi/rust-server-status-v2",
    },
  ],
  ge: [
    {
      img: "https://s6.uupload.ir/files/capture_ib.png",
      title: "Custom CMD",
      body: "Ein leistungsstarkes Befehlszeilentool zur mühelosen Verwaltung verschachtelter Routen-Aliasse. Vereinfacht das Hinzufügen, Entfernen und Ändern von Routen mit einer intuitiven CLI-Oberfläche.",
      link: "https://custom-cmd.tahanabavi.ir",
      github: "https://github.com/TahaNabavi/custom-cmd",
    },
    {
      img: "https://s6.uupload.ir/files/capture_a2yy.png",
      title: "Lebenslauf-Website",
      body: "Eine elegante, responsive Website, die meine Fähigkeiten, Projekte und Erfahrungen präsentiert. Mit modernen Webtechnologien für Geschwindigkeit und Stil entwickelt.",
      link: "https://resume-v1.tahanabavi.ir/",
      github: "",
    },
    {
      img: "https://s6.uupload.ir/files/capture_pq74.png",
      title: "Icon-Animations-Tool",
      body: "Erstelle mühelos beeindruckende SVG-Icon-Animationen. Perfekt für Designer und Entwickler, die dynamische Visuals in Projekte einbinden möchten.",
      link: "https://ico-animation.tahanabavi.ir/",
      github: "",
    },
    {
      img: "https://s6.uupload.ir/files/val_jb04.png",
      title: "Vaultify",
      body: "Sichere Aufbewahrung von Passwörtern, Aufgaben und Notizen mit moderner Verschlüsselung. Wichtige Daten gehen nie wieder verloren! 🚀🔒",
      link: "https://vaultify.tahanabavi.ir/",
      github: "https://github.com/TahaNabavi/vaultify-client",
    },
    {
      img: "https://camo.githubusercontent.com/a5d6e93b5aa0c13861e0d2de5b9307c4974980d303b779d8f4a24a712cd7aa5c/68747470733a2f2f73382e7575706c6f61642e69722f66696c65732f70315f7539656f2e706e67",
      title: "IRGAME-Shop",
      body: "Sicherer Kauf von Steam-Spielen, Gift Cards und digitalen Produkten. Ein reibungsloses Einkaufserlebnis für Gamer.",
      link: "",
      github: "https://github.com/TahaNabavi/iran-game",
    },
    {
      img: "https://s8.uupload.ir/files/pr1_7rjx.jpg",
      title: "Lebenslauf-Website",
      body: "Eine moderne Lebenslauf-Website mit Next.js, die Projekte und Fähigkeiten in einem cleanen, responsiven Design präsentiert.",
      link: "https://portfolio-gamma-flax-82.vercel.app/",
      github: "",
    },
    {
      img: "https://s8.uupload.ir/files/capture_0tpd.png",
      title: "Spielserver-Status",
      body: "Echtzeit-Dashboard für Spielserver-Status. Überprüfe Verfügbarkeit, Leistung und Spielerstatistiken.",
      link: "https://dark-game-pearl.vercel.app/",
      github: "https://github.com/TahaNabavi/rust-server-status-v2",
    },
  ],
};